name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bacherik/minetrack:latest
      
    - name: Docker Image Artifact Upload
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "bacherik/minetrack:latest"
